app:
  containerPort: 3000
  probesPath: /api/healthz
  envFrom:
  - secretRef:
      name: monsuivipsy-site-sealed-secret
  ingress:
    customHeaders:
      "Content-Security-Policy": "default-src 'none'; connect-src 'self' https://*.gouv.fr; font-src 'self'; media-src 'self' https://*.gouv.fr; img-src 'self' https://*.gouv.fr https://a.tile.openstreetmap.org https://b.tile.openstreetmap.org https://c.tile.openstreetmap.org; prefetch-src 'self' https://*.gouv.fr; script-src 'self' https://*.gouv.fr; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'"
      "X-Frame-Options": "deny"
      "X-XSS-Protection": "1; mode=block"
      "X-Content-Type-Options": "nosniff"
